### ISSUE TITLE
HTTPS Certificate issue on documentation site

### ISSUE THREAD

**Issue by pete-otaqui** [marklogic-community/grove#4]
Apologies if this is the wrong place to post this, but I was trying to view your documentation site for GROVE here:

https://wiki.marklogic.com/display/SAL/Grove+Developer+Starters+Guide

And unfortunately it seems that it's a self signed certificate (issued by ca-sha384.marklogic.com), which is causing an error.  I can bypass this to view the site obviously, but thought it was something you might want to fix.

**Comment by patrickmcelwee** [comment]
Thanks for reporting! We are in the process of migrating our documentation to be truly public here: https://marklogic-community.github.io/grove/guides/getting-started/ ... the link above is an internal company Wiki, which is why it is has a self-signed cert (that company employees have already trusted).

I'd be curious to know if there are specific parts of the docs you are looking for: it would help prioritize publishing them out to github.io.

**Comment by pete-otaqui** [comment]
Thanks for replying.

Actually I've been looking at a project based on the old AngularJS "Sample Stack", and wondered what you had in terms of a more modern set of front end tooling.

**Comment by Fristy89** [comment]
Iam Extending the front-end

**Comment by mariannemyers** [comment]
Closing.  This link has been removed.
